# Generated by Django 3.1 on 2021-10-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mercador_pago_id',
            new_name='mercado_pago_id',
        ),
    ]
