# Generated by Django 3.1 on 2021-11-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211115_2148'),
        ('payments', '0002_auto_20211018_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentModel',
        ),
    ]
