# Generated by Django 3.2.6 on 2021-09-16 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('name', models.CharField(max_length=256, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=250, verbose_name='Endereço')),
                ('number', models.CharField(max_length=250, verbose_name='Numero')),
                ('compliment', models.CharField(blank=True, max_length=250, verbose_name='Complemento')),
                ('district', models.CharField(max_length=250, verbose_name='Bairro')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=250, verbose_name='Cidade')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='orders.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='products.product')),
            ],
        ),
    ]
